#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("W3000.Android.Resource", IsApplication=true)]

namespace W3000.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_gallery = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnBad = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int btnGood = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int btnOpen = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int btnSoso = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int cbIsRandom = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imgWelcome = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int linearLayoutBottom = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int linearLayoutTop = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int mainMenuReview = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int mainMenuSave = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int mainViewPager = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int pbRating = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int txtChn = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int txtEng = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainViewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OpenFileLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainActivityMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
